/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mycompany.maestro.View;

import br.com.mycompany.maestro.Modelo.RN.ClienteRN;
import br.com.mycompany.maestro.Modelo.VO.Endereco;
import br.com.mycompany.maestro.Modelo.VO.Cliente;
import br.com.mycompany.maestro.Modelo.VO.Sexo;
import br.com.mycompany.maestro.Util.DataUtil;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Calendar;
import javax.swing.JOptionPane;





/**
 *
 * @author Natha
 */
public class CadCliente extends javax.swing.JFrame {

   
    private Long idAlteracao = 0L;
    private ClienteRN clienteRN;
    private Cliente cli;
    private Endereco end;
    private Sexo sex;
  
    public CadCliente() {
        this.clienteRN = new ClienteRN();
        this.cli = new Cliente();
        this.end = new Endereco();
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public CadCliente(Long idAlteracao) {
        this.clienteRN = new ClienteRN();
        this.cli = new Cliente();
        this.end = new Endereco();
        initComponents();
        setLocationRelativeTo(null);
        this.idAlteracao = idAlteracao;
        try{
            Cliente cliRecuperado = clienteRN.listarUm(idAlteracao);
            txt_id.setText(String.valueOf(cliRecuperado.getCodigo()));
            txt_nome.setText(cliRecuperado.getNome());
            txt_bairro.setText(cliRecuperado.getEndereco().getBairro());
            txt_cep.setText(cliRecuperado.getEndereco().getCep());
            txt_cidade.setText(cliRecuperado.getEndereco().getCidade());
            txt_complemento.setText(cliRecuperado.getEndereco().getComplemento());
            txt_estado.setText(cliRecuperado.getEndereco().getEstado());
            txt_cpf.setText(cliRecuperado.getCpf());
            txt_rg.setText(cliRecuperado.getRg());
            txt_email.setText(cliRecuperado.getEmail());
            txt_telefone.setText(cliRecuperado.getTelefone());
            jd_dtnas.setDate(DataUtil.converteLocalDateToDate(cliRecuperado.getDtnas()));
            if(cliRecuperado.getSexo() == sex.FEMININO){
                rb_fem.setSelected(true);
            }
            else
            {
                rb_masc.setSelected(true);
            }
            txt_logradouro.setText(cliRecuperado.getEndereco().getLogradouro());
            txt_numero.setText(cliRecuperado.getEndereco().getNumero());
            checkAtivo.setSelected(cliRecuperado.getStatus());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_dtnasc = new javax.swing.JLabel();
        jd_dtnas = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txt_logradouro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_complemento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JTextField();
        lbl_cpf = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JTextField();
        lbl_rg = new javax.swing.JLabel();
        txt_rg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rb_masc = new javax.swing.JRadioButton();
        rb_fem = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_estado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        checkAtivo = new javax.swing.JCheckBox();
        btn_cancelar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-id.png")); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, -1, -1));

        txt_id.setEditable(false);
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, 60, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-user.png")); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 100, -1));
        getContentPane().add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 220, 30));

        lbl_dtnasc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_dtnasc.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-date.png")); // NOI18N
        lbl_dtnasc.setText("Data de Nascimento:");
        getContentPane().add(lbl_dtnasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 170, -1));
        getContentPane().add(jd_dtnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-housenum.png")); // NOI18N
        jLabel3.setText("Logradouro:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));
        getContentPane().add(txt_logradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 220, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-housenum.png")); // NOI18N
        jLabel11.setText("Complemen.:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));
        getContentPane().add(txt_complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-cep.png")); // NOI18N
        jLabel6.setText("CEP:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, 40));
        getContentPane().add(txt_cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-housenum.png")); // NOI18N
        jLabel5.setText("Bairro:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));
        getContentPane().add(txt_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 220, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-email.png")); // NOI18N
        jLabel12.setText("Email:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, -1, -1));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 210, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-phone2.png")); // NOI18N
        jLabel13.setText("Telefone:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 110, -1));
        getContentPane().add(txt_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 210, 30));

        lbl_cpf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_cpf.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-cpf-rg.png")); // NOI18N
        lbl_cpf.setText("CPF:");
        getContentPane().add(lbl_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));
        getContentPane().add(txt_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 210, 30));

        lbl_rg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_rg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-cpf-rg.png")); // NOI18N
        lbl_rg.setText("RG:");
        getContentPane().add(lbl_rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));
        getContentPane().add(txt_rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 210, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-x.png")); // NOI18N
        jLabel4.setText("Sexo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        rb_masc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rb_masc.setText("Masculino");
        getContentPane().add(rb_masc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        rb_fem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rb_fem.setText("Feminino");
        getContentPane().add(rb_fem, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-housenum.png")); // NOI18N
        jLabel8.setText("Nº:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, -1, -1));
        getContentPane().add(txt_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 40, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-city.png")); // NOI18N
        jLabel7.setText("Cidade:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));
        getContentPane().add(txt_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\icon-sity.png")); // NOI18N
        jLabel9.setText("Estado:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, -1));
        getContentPane().add(txt_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 220, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Status:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 50, 40));

        checkAtivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkAtivo.setText("Ativo");
        getContentPane().add(checkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 60, 40));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 710, 80, 50));

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 710, 80, 50));

        jLabelFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\Símbolo-Direito.png")); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 600, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed

        try{
            if(this.idAlteracao == 0){
                cli.setNome(txt_nome.getText());
                cli.setStatus(checkAtivo.isSelected());
                cli.setCpf(txt_cpf.getText());
                cli.setRg(txt_rg.getText());

                Calendar datanasCalendar = jd_dtnas.getCalendar();
                LocalDate datanasLocalDate = LocalDateTime.ofInstant(datanasCalendar.toInstant(), datanasCalendar.getTimeZone().toZoneId()).toLocalDate();
                cli.setDtnas(datanasLocalDate);

                if(rb_fem.isSelected()){
                    cli.setSexo(Sexo.FEMININO);
                }
                else
                {
                    cli.setSexo(Sexo.MASCULINO);
                }

                cli.setEmail(txt_email.getText());
                cli.setTelefone(txt_telefone.getText());
                end.setBairro(txt_bairro.getText());
                end.setCep(txt_cep.getText());
                end.setCidade(txt_cidade.getText());
                end.setComplemento(txt_complemento.getText());
                end.setEstado(txt_estado.getText());
                end.setLogradouro(txt_logradouro.getText());
                end.setNumero(txt_numero.getText());
                cli.setEndereco(end);

                this.clienteRN.salvar(cli);
            }else{
                Cliente cliRecuperado = clienteRN.listarUm(idAlteracao);
                cliRecuperado.setNome(this.txt_nome.getText());
                cliRecuperado.setStatus(checkAtivo.isSelected());
                cliRecuperado.setCpf(txt_cpf.getText());
                cliRecuperado.setRg(txt_rg.getText());

                Calendar datanasCalendar = jd_dtnas.getCalendar();
                LocalDate datanasLocalDate = LocalDateTime.ofInstant(datanasCalendar.toInstant(), datanasCalendar.getTimeZone().toZoneId()).toLocalDate();
                cliRecuperado.setDtnas(datanasLocalDate);

                if(rb_fem.isSelected()){
                    cliRecuperado.setSexo(Sexo.FEMININO);
                }
                else
                {
                    cliRecuperado.setSexo(Sexo.MASCULINO);
                }

                cliRecuperado.setEmail(txt_email.getText());
                cliRecuperado.setTelefone(txt_telefone.getText());
                end.setBairro(txt_bairro.getText());
                end.setCep(txt_cep.getText());
                end.setCidade(txt_cidade.getText());
                end.setComplemento(txt_complemento.getText());
                end.setEstado(txt_estado.getText());
                end.setLogradouro(txt_logradouro.getText());
                end.setNumero(txt_numero.getText());
                cliRecuperado.setEndereco(end);

                this.clienteRN.atualizar(cliRecuperado);
            }
            JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JCheckBox checkAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFundo;
    private com.toedter.calendar.JDateChooser jd_dtnas;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_dtnasc;
    private javax.swing.JLabel lbl_rg;
    private javax.swing.JRadioButton rb_fem;
    private javax.swing.JRadioButton rb_masc;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_cep;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_complemento;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_logradouro;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_rg;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
