/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mycompany.maestro.View;

import ServicoEmail.Correio;
import br.com.mycompany.maestro.Modelo.RN.ClienteRN;
import br.com.mycompany.maestro.Modelo.RN.ProcessoRN;
import br.com.mycompany.maestro.Modelo.RN.AcaoRN;
import br.com.mycompany.maestro.Modelo.RN.EstagiarioRN;
import br.com.mycompany.maestro.Modelo.RN.OrdemRN;
import br.com.mycompany.maestro.Modelo.VO.Cliente;
import br.com.mycompany.maestro.Modelo.VO.Acao;
import static br.com.mycompany.maestro.Modelo.VO.Cliente_.processo;
import br.com.mycompany.maestro.Modelo.VO.Processo;
import br.com.mycompany.maestro.Modelo.VO.Ordem;
import br.com.mycompany.maestro.Modelo.VO.EstadoProcesso;
import br.com.mycompany.maestro.Modelo.VO.Estagiario;
import br.com.mycompany.maestro.Util.DataUtil;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.List;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Natha
 */
public class CadProcesso extends javax.swing.JFrame {
  private Long idAlteracao = 0L;
    private List<Acao> acoes;
    private AcaoRN acaoRN;
    private List<Cliente> cli;
    private ClienteRN clienteRN;
    private List<Estagiario> estagiarios;
    private EstagiarioRN estagiarioRN;
    private Processo ps;
    private Processo psSalt;
    private ProcessoRN processoRN;
    private List<Estagiario> estager;
    private Processo Processo;
    
    public CadProcesso() {
        this.acaoRN = new AcaoRN();
        this.clienteRN = new ClienteRN();
        this.estagiarioRN = new EstagiarioRN();
        this.processoRN = new ProcessoRN();
        initComponents();
        setLocationRelativeTo(null);
        this.popularComboCliente();
        this.popularComboAcao();
        this.popularComboEstagiario();
        this.popularComboEstadoProcesso();
    }
    
        public CadProcesso(Long idAlteracao) {
        initComponents();
        this.acaoRN = new AcaoRN();
        this.clienteRN = new ClienteRN();
        this.estagiarioRN = new EstagiarioRN();
        this.processoRN = new ProcessoRN();
        setLocationRelativeTo(null);
        this.idAlteracao = idAlteracao;
        try{
            ps = processoRN.listarUm(idAlteracao);
            psSalt = processoRN.listarUm(idAlteracao);
            txt_id.setText(String.valueOf(psSalt.getCodigo()));
            ta_pro.setText(psSalt.getCausa());      
            jd_ent.setDate(DataUtil.converteLocalDateToDate(psSalt.getDtent()));
            jd_sai.setDate(DataUtil.converteLocalDateToDate(psSalt.getDtsaida()));
            
            ta_p.setText(psSalt.getIndiciado());
            ta_s.setText(psSalt.getServico());  
            txt_valort.setText(String.valueOf(ps.getValort()));
            popularComboClienteEdicao(idAlteracao);
            popularComboEstagiarioEdicao(idAlteracao);
            popularComboAcaoEdicao(idAlteracao);
            popularComboEstadoProcessoEdicao(idAlteracao);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jd_ent = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jd_sai = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cb_cliente = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cb_estager = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cb_estadoProcesso = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cb_acao = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_pro = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_p = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        txt_valort = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_s = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nº Processo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txt_id.setEditable(false);
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dt. Entrada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));
        getContentPane().add(jd_ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dt. Saída");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));
        getContentPane().add(jd_sai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cliente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        cb_cliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cb_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 140, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estágiario");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        getContentPane().add(cb_estager, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 150, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado Processo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        getContentPane().add(cb_estadoProcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ação Judicial");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, -1));

        getContentPane().add(cb_acao, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 140, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Causa");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        ta_pro.setColumns(20);
        ta_pro.setRows(5);
        jScrollPane1.setViewportView(ta_pro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 420, 240));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Indiciado");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 70, -1));

        ta_p.setColumns(20);
        ta_p.setRows(5);
        jScrollPane2.setViewportView(ta_p);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 280, 100));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Valor Total");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 290, -1, 20));
        getContentPane().add(txt_valort, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 330, 170, 30));

        ta_s.setColumns(20);
        ta_s.setRows(5);
        jScrollPane6.setViewportView(ta_s);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 280, 100));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Serviços Extras");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, -1, 40));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 380, -1, 40));

        jLabel_Background.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\Menu-Background.png")); // NOI18N
        getContentPane().add(jLabel_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
              try{
            if(this.idAlteracao == 0){
                ps = new Processo();
                ps.setCausa(ta_pro.getText());
                ps.setIndiciado(ta_p.getText());
                ps.setServicosExtras(ta_s.getText());
                ps.setValort(new Double(txt_valort.getText()));

                Calendar dataentCalendar = jd_ent.getCalendar();
                LocalDate dataentLocalDate = LocalDateTime.ofInstant(dataentCalendar.toInstant(), dataentCalendar.getTimeZone().toZoneId()).toLocalDate();
                ps.setDtent(dataentLocalDate);

                Calendar datasaiCalendar = jd_sai.getCalendar();

                LocalDate datasaiLocalDate = LocalDateTime.ofInstant(datasaiCalendar.toInstant(), datasaiCalendar.getTimeZone().toZoneId()).toLocalDate();
                ps.setDtsaida(datasaiLocalDate);

                ps.setCliente((Cliente)this.getClienteSelecionado(cb_cliente.getSelectedIndex()));
                ps.setEstagiario((Estagiario)this.getEstagiarioSelecionado(cb_estager.getSelectedIndex()));
                ps.setAcao((Acao)this.getAcaoSelecionado(cb_acao.getSelectedIndex()));
                ps.setEstadoProcesso((EstadoProcesso)this.getEstadoProcessoSelecionado(cb_estadoProcesso.getSelectedIndex()));

                processoRN.salvar(ps);

            }else{
                ps.setCausa(ta_pro.getText());
                ps.setIndiciado(ta_p.getText());
                ps.setServicosExtras(ta_s.getText());
                ps.setValort(new Double(txt_valort.getText()));

                Calendar dataentCalendar = jd_ent.getCalendar();
                LocalDate dataentLocalDate = LocalDateTime.ofInstant(dataentCalendar.toInstant(), dataentCalendar.getTimeZone().toZoneId()).toLocalDate();
                ps.setDtent(dataentLocalDate);

                Calendar datasaiCalendar = jd_sai.getCalendar();
                LocalDate datasaiLocalDate = LocalDateTime.ofInstant(datasaiCalendar.toInstant(), datasaiCalendar.getTimeZone().toZoneId()).toLocalDate();
                ps.setDtsaida(datasaiLocalDate);

                ps.setCliente((Cliente)this.getClienteSelecionado(cb_cliente.getSelectedIndex()));
                ps.setEstagiario((Estagiario)this.getEstagiarioSelecionado(cb_estager.getSelectedIndex()));
                ps.setAcao((Acao)this.getAcaoSelecionado(cb_acao.getSelectedIndex()));
                ps.setEstadoProcesso((EstadoProcesso)this.getEstadoProcessoSelecionado(cb_estadoProcesso.getSelectedIndex()));

                processoRN.atualizar(ps);
            }
            
            Correio correio = new Correio();
            correio.NotificarPorEmail(ps);
            JOptionPane.showMessageDialog(this, "Processo cadastrado com sucesso, Verifique sua caixa de email!");
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void popularComboCliente() {
        ComboBoxModel modelocli;
            try {
                    Vector linhas = new Vector();
                    cli = clienteRN.listaTodos();
                
                for (Cliente c : cli)
                {
                    Vector linha = new Vector();
                    linha.add(c.getCodigo());
                    linha.add(c.getNome());
                    linhas.add(linha);
                }
                modelocli = new DefaultComboBoxModel(linhas);
                cb_cliente.setModel(modelocli);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }
    
     private void popularComboClienteEdicao(Long id) {
        ComboBoxModel modelocli;
            try {
                    Vector linhas = new Vector();
                    cli = clienteRN.listaTodos();
                    int index = 0;
                    int indexSelecionado = 0;
                    for (Cliente c : cli)
                {
                    Vector linha = new Vector();
                    linha.add(c.getCodigo());
                    linha.add(c.getNome());
                    linhas.add(linha);
                    
                    if(ps.getCliente().getCodigo() == c.getCodigo()){
                        indexSelecionado = index;
                    }
                    index++;
                }
                modelocli = new DefaultComboBoxModel(linhas);
                cb_cliente.setModel(modelocli);
                cb_cliente.setSelectedIndex(indexSelecionado);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }
     
    private Object getClienteSelecionado(int posicao){
        Cliente c = new Cliente();
        c = (Cliente) cli.get(posicao);

        return c;
    }

    
    private void popularComboEstagiario() {
        ComboBoxModel modeloEstager;
            try {
                    Vector linhas = new Vector();
                    estager = estagiarioRN.listaTodos();
                
                for (Estagiario e : estager)
                {
                    Vector linha = new Vector();
                    linha.add(e.getCodigo());
                    linha.add(e.getNome());
                    linhas.add(linha);
                }
                modeloEstager = new DefaultComboBoxModel(linhas);
                cb_estager.setModel(modeloEstager);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }
        private void popularComboEstagiarioEdicao(Long id) {
        ComboBoxModel modeloestager;
            try {
                    Vector linhas = new Vector();
                    estager = estagiarioRN.listaTodos();
                    int index = 0;
                    int indexSelecionado = 0;
                    for (Estagiario e : estager)
                    {
                        Vector linha = new Vector();
                        linha.add(e.getCodigo());
                        linha.add(e.getNome());
                        linhas.add(linha);

                        if(ps.getEstagiario().getCodigo() == e.getCodigo()){
                            indexSelecionado = index;
                        }
                        index++;
                    }
                modeloestager = new DefaultComboBoxModel(linhas);
                cb_estager.setModel(modeloestager);
                cb_estager.setSelectedIndex(indexSelecionado);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }
    private Object getEstagiarioSelecionado(int posicao) 
    {
        Estagiario e = new Estagiario();
        e = (Estagiario) estager.get(posicao);

        return e;
    }
    private void popularComboAcao() {
        ComboBoxModel modeloacao;
            try {
                Vector linhas = new Vector();
                acoes = acaoRN.listaTodos();
                
                for (Acao a : acoes)
                {
                    Vector linha = new Vector();
                    linha.add(a.getCodigo());
                    linha.add(a.getDescricao());
                    linhas.add(linha);
                }
                modeloacao = new DefaultComboBoxModel(linhas);
                cb_acao.setModel(modeloacao);
            } catch (Exception a) {
                a.printStackTrace();
            }
    }
    
    private void popularComboAcaoEdicao(Long id) {
        ComboBoxModel modeloacao;
            try {
                Vector linhas = new Vector();
                acoes = acaoRN.listaTodos();
                int index = 0;
                int indexSelecionado = 0;
                for (Acao a : acoes)
                {
                    Vector linha = new Vector();
                    linha.add(a.getCodigo());
                    linha.add(a.getDescricao());
                    linhas.add(linha);
                    
                    if(ps.getAcao().getCodigo() == a.getCodigo()){
                        indexSelecionado = index;
                    }
                    index++;
                }
                modeloacao = new DefaultComboBoxModel(linhas);
                cb_acao.setModel(modeloacao);
                cb_acao.setSelectedIndex(indexSelecionado);
            } catch (Exception a) {
                a.printStackTrace();
            }
    }
    
    private Object getAcaoSelecionado(int posicao) 
    {
        Acao a = new Acao();
        a = (Acao) acoes.get(posicao);

        return a;
    }
    
    private void popularComboEstadoProcesso() {
        ComboBoxModel modelosts;
            try {
                    Vector linhas = new Vector();

                    Vector concluido = new Vector();
                    concluido.add(EstadoProcesso.CONCLUIDO);
                    linhas.add(concluido);

                    Vector analise = new Vector();
                    analise.add(EstadoProcesso.ANALISE);
                    linhas.add(analise);

                    Vector andamento = new Vector();
                    andamento.add(EstadoProcesso.ANDAMENTO);
                    linhas.add(andamento);

                    Vector cancelado = new Vector();
                    cancelado.add(EstadoProcesso.CANCELADO);
                    linhas.add(cancelado);

                    modelosts = new DefaultComboBoxModel(linhas);
                    cb_estadoProcesso.setModel(modelosts);
            } catch (Exception e) {

                    e.printStackTrace();
            }
    }
    
      private void popularComboEstadoProcessoEdicao(Long id) {
        ComboBoxModel modelosts;
            try {
                    Vector linhas = new Vector();

                    Vector concluido = new Vector();
                    concluido.add(EstadoProcesso.CONCLUIDO);
                    linhas.add(concluido);

                    Vector analise = new Vector();
                    analise.add(EstadoProcesso.ANALISE);
                    linhas.add(analise);

                    Vector andamento = new Vector();
                    andamento.add(EstadoProcesso.ANDAMENTO);
                    linhas.add(andamento);

                    Vector cancelado = new Vector();
                    cancelado.add(EstadoProcesso.CANCELADO);
                    linhas.add(cancelado);

                    modelosts = new DefaultComboBoxModel(linhas);
                    cb_estadoProcesso.setModel(modelosts);
                    
                if (ps.getEstadoProcesso().equals(EstadoProcesso.CONCLUIDO)) {
                    cb_estadoProcesso.setSelectedIndex(0);
                } 
                else if (ps.getEstadoProcesso().equals(EstadoProcesso.ANALISE))
                {
                    cb_estadoProcesso.setSelectedIndex(1);
                }
                else if (ps.getEstadoProcesso().equals(EstadoProcesso.ANDAMENTO))
                {
                    cb_estadoProcesso.setSelectedIndex(2);
                }
                else
                {
                    cb_estadoProcesso.setSelectedIndex(3);
                }
            } catch (Exception e) {

                    e.printStackTrace();
            }
    }
      
          private Object getEstadoProcessoSelecionado(int posicao) 
    {
        EstadoProcesso ep;
        if (cb_estadoProcesso.getSelectedIndex() == 0) 
        {
            ep = EstadoProcesso.CONCLUIDO;
        } 
        else if (cb_estadoProcesso.getSelectedIndex() == 1)  
        {
            ep = EstadoProcesso.ANALISE;
        }
        else if (cb_estadoProcesso.getSelectedIndex() == 2)  
        {
            ep = EstadoProcesso.ANDAMENTO;
        }
        else
        {
            ep = EstadoProcesso.CANCELADO;
        }
        
        return ep;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProcesso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox cb_acao;
    private javax.swing.JComboBox cb_cliente;
    private javax.swing.JComboBox cb_estadoProcesso;
    private javax.swing.JComboBox cb_estager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private com.toedter.calendar.JDateChooser jd_ent;
    private com.toedter.calendar.JDateChooser jd_sai;
    private javax.swing.JTextArea ta_p;
    private javax.swing.JTextArea ta_pro;
    private javax.swing.JTextArea ta_s;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_valort;
    // End of variables declaration//GEN-END:variables
}
