/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mycompany.maestro.View;

import br.com.mycompany.maestro.Modelo.RN.ProcessoRN;
import br.com.mycompany.maestro.Modelo.VO.Processo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Natha
 */

public class ViewMain extends javax.swing.JFrame {

    private List<Processo> processos;
    private ProcessoRN processoRN;
    
    public ViewMain() {
        processoRN = new ProcessoRN();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_cli = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ps = new javax.swing.JTable();
        btn_cancelar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jLabel_Background = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jm_cad = new javax.swing.JMenu();
        im_usuario = new javax.swing.JMenuItem();
        im_cli = new javax.swing.JMenuItem();
        im_estagiario = new javax.swing.JMenuItem();
        im_acao = new javax.swing.JMenuItem();
        im_ordem = new javax.swing.JMenuItem();
        im_servicoprestado = new javax.swing.JMenuItem();
        jm_ps = new javax.swing.JMenu();
        jm_ajuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 60, 20));
        getContentPane().add(txt_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 14, 534, 30));

        btn_pesquisar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        tb_ps.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tb_ps.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tb_ps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Processo", "Data Entrada", "Data Fim", "Causa", "Cliente", "Estágiario", "Indiciado", "Serviço Prestado", "Valor Total", "Estado Processo", "Ação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_ps);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 84, 1030, 365));

        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cancelar.setText("Sair");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 473, 100, 30));

        btn_alterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 473, 90, 30));

        btn_excluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_excluir.setForeground(java.awt.Color.red);
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 473, 70, 30));

        jLabel_Background.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Natha\\OneDrive\\Área de Trabalho\\POO2\\View Imagens\\Menu-Background.png")); // NOI18N
        getContentPane().add(jLabel_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 540));

        jMenuBar2.setBorder(null);

        jm_cad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jm_cad.setText("Cadastro");

        im_usuario.setText("Usuário");
        im_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_usuarioActionPerformed(evt);
            }
        });
        jm_cad.add(im_usuario);

        im_cli.setText("Cliente");
        im_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_cliActionPerformed(evt);
            }
        });
        jm_cad.add(im_cli);

        im_estagiario.setText("Estágiario");
        im_estagiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_estagiarioActionPerformed(evt);
            }
        });
        jm_cad.add(im_estagiario);

        im_acao.setText("Ação");
        im_acao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_acaoActionPerformed(evt);
            }
        });
        jm_cad.add(im_acao);

        im_ordem.setText("Ordem");
        im_ordem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_ordemActionPerformed(evt);
            }
        });
        jm_cad.add(im_ordem);

        im_servicoprestado.setText("Serviço Prestado");
        im_servicoprestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_servicoprestadoActionPerformed(evt);
            }
        });
        jm_cad.add(im_servicoprestado);

        jMenuBar2.add(jm_cad);

        jm_ps.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jm_ps.setText("Ordem de Serviço");
        jm_ps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_psMouseClicked(evt);
            }
        });
        jMenuBar2.add(jm_ps);

        jm_ajuda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jm_ajuda.setText("Ajuda");
        jMenuBar2.add(jm_ajuda);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void im_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_usuarioActionPerformed
        new ViewUser().setVisible(true);
    }//GEN-LAST:event_im_usuarioActionPerformed

    private void im_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_cliActionPerformed
        new ViewCliente().setVisible(true);
    }//GEN-LAST:event_im_cliActionPerformed

    private void im_estagiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_estagiarioActionPerformed
        new ViewEstagiario().setVisible(true);
    }//GEN-LAST:event_im_estagiarioActionPerformed

    private void im_acaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_acaoActionPerformed
        new ViewAcao().setVisible(true);
    }//GEN-LAST:event_im_acaoActionPerformed

    private void im_ordemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_ordemActionPerformed
        new ViewOrdem().setVisible(true);
    }//GEN-LAST:event_im_ordemActionPerformed

    private void im_servicoprestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_servicoprestadoActionPerformed
        new ViewServicoPrestado().setVisible(true);
    }//GEN-LAST:event_im_servicoprestadoActionPerformed

    private void jm_psMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_psMouseClicked
        new CadProcesso().setVisible(true);
    }//GEN-LAST:event_jm_psMouseClicked

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        String filtro = txt_cli.getText();

        try {
            DefaultTableModel model = (DefaultTableModel) tb_ps.getModel();
            model.setNumRows(0);
            this.processos = processoRN.listarFitroLike(filtro);

            for (Processo ps : processos) {
                String[] linha = {String.valueOf(ps.getCodigo()), String.valueOf(ps.getDtent()), String.valueOf(ps.getDtsaida()), ps.getCausa() ,ps.getCliente().getNome(),
                    ps.getEstagiario().getNome(), ps.getIndiciado(), ps.getServicosExtras(), String.valueOf(ps.getValort()), String.valueOf(ps.getEstadoProcesso()), String.valueOf(ps.getAcao().getCodigo())};
                model.addRow(linha);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        int linha = this.tb_ps.getSelectedRow();
        Long id = Long.valueOf(tb_ps.getValueAt(linha, 0).toString());
        new CadProcesso(id).setVisible(true);
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        try{
            int linha = this.tb_ps.getSelectedRow();
            Long id = Long.valueOf(tb_ps.getValueAt(linha, 0).toString());
            Processo prcFind = processoRN.listarUm(id);
            processoRN.excluir(prcFind);

            DefaultTableModel model = (DefaultTableModel) tb_ps.getModel();
            model.removeRow(linha);
            JOptionPane.showMessageDialog(this, "Processo Excluído com Sucesso!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JMenuItem im_acao;
    private javax.swing.JMenuItem im_cli;
    private javax.swing.JMenuItem im_estagiario;
    private javax.swing.JMenuItem im_ordem;
    private javax.swing.JMenuItem im_servicoprestado;
    private javax.swing.JMenuItem im_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Background;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jm_ajuda;
    private javax.swing.JMenu jm_cad;
    private javax.swing.JMenu jm_ps;
    private javax.swing.JTable tb_ps;
    private javax.swing.JTextField txt_cli;
    // End of variables declaration//GEN-END:variables
}
